### ISSUE TITLE
End-to-End Quantization for Speedup and Memory Savings: Inviting Contributions!

### ISSUE THREAD

**Issue by Xiuyu-Li** [Xiuyu-Li/q-diffusion#23]
As many of you have asked, the current implementation is solely simulated quantization and doesn't have real benefits on speedup or memory savings. I have thought about tackling this challenge and devised a plan broken down into three steps:

- [ ] **Step 1: Direct Loading of Checkpoints with Quantizers #16** - Originally, the codebase was adapted from the SD implementation, loading the FP32 SD model checkpoint first and then the checkpoint with calibrated quantizers for convenience. However, direct loading of the checkpoint with quantizers (without initially loading the FP32 checkpoint) is feasible and can be accomplished with minor modifications to the existing Python code.

- [ ] **Step 2: Implement Weight-Only Quantization #3 #7 #9 #12 #14** - The current simulated quantization, operating in FP32, ironically requires more VRAM. It needs to take more memory to store the quantizers (especially for AdaRound configs) and perform on-the-fly quantization. A straightforward interim solution is to quantize only the model weights and dynamically dequantize each layer for computation. This approach is particularly useful when the model weights (not activations) dominates the VRAM usage, which is often the case when batch size is small and model is large (e.g. SD-XL). For reference, many LLM codebases like [FastChat](https://github.com/lm-sys/FastChat/blob/main/fastchat/model/compression.py) have incorporated this strategy, and it shouldn't be difficult to adapt their implementation for our case.

- [ ] **Step 3: Implement End-to-End Quantization #7 #15** - The implementation of comprehensive end-to-end quantization will substantially reduce memory usage while providing speedup. Nevertheless, this step is challenging since there are no off-the-shelf libraries for quantizing diffusion model U-Nets, particularly their conv layers. I have done thorough research and concludes that [CUTLASS](https://github.com/NVIDIA/cutlass) could be a viable tool for this task, which supports INT8 conv [[1]](https://github.com/NVIDIA/cutlass/issues/978)[[2]](https://github.com/NVIDIA/cutlass/blob/main/test/unit/conv/device/conv2d_fprop_implicit_gemm_s8nhwc_s8nhwc_s32nhwc_tensor_op_s32_sm80.cu) and linear (following [torch-int](https://github.com/Guangxuan-Xiao/torch-int/blob/main/torch_int/kernels/linear.cu)). layers. This tool allows for granular, kernel-level control over the loading of calibrated quantizer configurations. While [Triton](https://github.com/openai/triton) and [TVM](https://github.com/apache/tvm/tree/main/python/tvm/relay/qnn) are also worth considering, I have reservations about the former’s lack of community support and the latter's development complexity (during our experience with [HAWQ](https://github.com/Zhen-Dong/HAWQ/blob/main/tvm_benchmark/README.md)). I am leaning towards not going with [PyTorch's native quantization](https://pytorch.org/docs/stable/quantization.html) or other third-party libraries, as they often have significant limitations regarding the loading of customized quantizer configurations and performance optimization.

I previously planned to gradually work on the steps outlined above. However, due to other pressing commitments, I am not able to have a definitive timeline for this project. While I anticipate addressing Step 1 shortly and Step 2 in the future when I find time, Step 3’s development and testing phase is currently undefined. I welcome contributions from anyone interested in realizing this end-to-end implementation, as there is currently no open-source, quantized SD implementation available for CUDA GPUs. 

Please don’t hesitate to share your thoughts or suggest alternative approaches to this issue!

**Comment by danieltanhx** [comment]
this is a show stopper. Cannot proceed further using google colab or kaggle since their VRAM limited to 16GB

**Comment by Xiuyu-Li** [comment]
We'd like to acknowledge the contribution from the NVIDIA team, which has led to the integration of an optimized end-to-end implementation for quantized stable diffusion on CUDA GPUs in [the latest updates of TensorRT](https://developer.nvidia.com/blog/tensorrt-accelerates-stable-diffusion-nearly-2x-faster-with-8-bit-post-training-quantization/), now featuring our Q-Diffusion! ([example](https://github.com/NVIDIA/TensorRT/tree/release/9.3/demo/Diffusion#faster-text-to-image-using-sdxl--int8-quantization-using-ammo))

As a result of this progress, I'll be closing several issues related to developing more efficient SD applications using quantization (#1 #7 #12 #15). This repository primarily focuses on academic research into SD quantization. Issues requesting a more streamlined implementation of Q-Diffusion framework (e.g. #16) will remain open for further discussion and development.
